# ---------------------------------------------------------------------------- #
#                           DATABRICKS RUNTIME BLOCK                           #
# ---------------------------------------------------------------------------- #

db_variables:
  git_branch: &git_branch main
  pipeline_name: &pipeline_name ANN_test
  trial_settings: &trial_settings
    max_retries: 1
    min_retry_interval_millis: 300000
    retry_on_timeout: true
    timeout_seconds: 3600

  owner_email_id: &owner_email_id chirag.lodaya@zebra.com
  job_email_notification_settings: &job_email_notification_settings
    email_notifications:
      on_failure:
      - chirag.lodaya@zebra.com
      no_alert_for_skipped_runs: false
  task_email_notification_settings: &task_email_notification_settings
    email_notifications:
      on_failure:
      - chirag.lodaya@zebra.com
    notification_settings:
      no_alert_for_skipped_runs: false
      no_alert_for_canceled_runs: false
      alert_on_last_attempt: false

  init_scripts : &init_script dbfs:/FileStore/init_script_template.sh
  runtime_version_cpu10: &runtimecpu10 10.4.x-cpu-ml-scala2.12
  runtime_version_cpu9: &runtimecpu9 9.1.x-cpu-ml-scala2.12
  runtime_version_gpu10: &runtimegpu10 10.4.x-gpu-ml-scala2.12
  cpu_pool: &cpu_pool_type_settings
    driver_pool: 0610-213241-sough6-pool-BePOyOTb
  cpu_node: &cpu_node_type_settings
    azure_attributes:
      availability: ON_DEMAND_AZURE
    node_type_id: Standard_F16s_v2
    driver_node_type_id: Standard_F16s_v2
    enable_elastic_disk: true



# ---------------------------------------------------------------------------- #
#                                  MAIN BLOCK                                  #
# ---------------------------------------------------------------------------- #


build:
  no_build: true
environments:
  EXP1:
    workflows:
    - name: *pipeline_name
      <<: *job_email_notification_settings
      webhook_notifications: {}

      timeout_seconds: 28800
      max_concurrent_runs: 1
      tasks:
      - task_key: ANN_test_key
        spark_python_task:
          python_file: Workspace/Repos/chirag.lodaya@zebra.com/MLO_test/ANN.py
          source: GIT
        new_cluster:
          cluster_name: ''
          spark_version: *runtimecpu10
          spark_conf:
            spark.databricks.cluster.profile: singleNode
            spark.master: local[*, 4]
          custom_tags:
            ResourceClass: SingleNode
            job_name: *pipeline_name
            task_name: ann_test_task
          init_scripts:
          - dbfs:
              destination: *init_script
          <<: *cpu_node_type_settings
          driver_node_type_id: Standard_F16s_v2
          num_workers: 0
        <<: *trial_settings
        <<: *task_email_notification_settings
      git_source:
        git_url: https://github.com/chiraglodaya-zebra/MLO_test.git
        git_provider: gitHubEnterprise
        git_branch: *git_branch
      access_control_list:
        - user_name: *owner_email_id
          permission_level: "IS_OWNER"      
        - group_name: "users"
          permission_level: "CAN_VIEW"            
        - group_name : "Level2"
          permission_level : "CAN_MANAGE_RUN"             
      format: MULTI_TASK
