experiment_name: ${now:%Y-%m-%d}_now:%H:%M:%S
hydra:
    mode: MULTIRUN
    sweep:
      dir: C:/Users/cl5495/Desktop/ML_Ops_Exp/MLO_test/mlflow_op/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
      subdir: ${hydra.job.num}
    sweeper:
        params:
          +window_size: 3,4
          +creation_did: 47, 48 

