hydra:
    mode: MULTIRUN
    sweep:
      dir: /dbfs/FileStore/MLO_Test_Temp/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
      subdir: ${hydra.job.num}
    sweeper:
        params:
          +window_size: 3
          +creation_did: 47

    
