hydra:
    mode: MULTIRUN
    sweep:
      dir: /dbfs/mnt/qa1datamartstdsandbox/qa1datamartstdsandbox-ds-store-std-sandbox-rw/ML_Ops_Exp_arjun/multirun/${now:%Y-%m-%d}/Exp_1
      subdir: ${hydra.job.override_dirname}
    sweeper:
        params:
          +window_size: 3,4
          +creation_did: 47,48

    
